FORMAT: 1A
HOST: https://mensa.dreami.ch/v1

# HSR Mensa API

The HSR Mensa API lets you get information about the menus at the HSR mensa.

It scrapes the HSR Mensa page for you and extracts the needed information. This frees you from keeping your own scraper up-to-date and you can concentrate on actually writing a good app.



# Technical Briefing

The enumeration values for `site` are currently:

* `mensa`
* `forschungszentrum`

The enumeration values for `weekday` are currently:

* `mon`
* `tue`
* `wed`
* `thu`
* `fri`
* `today`: Defaults to today, if on a weekend: `fri`

Note that we can only display upcoming days (if on a weekend, the past week) since we scrap once each day and we don't cache anything from earlier days.

## Get a site [/sites/{site}]

Get information about a site (all upcoming weekdays)

+ Parameters
    + site: mensa (string) - Site name

### Get a single site [GET]

+ Response 200 (application/json)

    + Body

            {
                "site": "SiteType.MENSA",
                "days": [
                    {
                        "weekday": "Fr"
                        "date": "12.05.",
                        "menus": [
                            {
                                "description": "Merrfischchnusperli im Bierteig ",
                                "title": "Fish & Chips"
                            },
                            {
                                "description": "mit Menusalat",
                                "title": "Älpler Chääs Hörnli"
                            },
                            {
                                "description": "Kräuterbutter, Tagesbeilage und Gemüse vom Free Choice",
                                "title": "Schweins\u00adsteak vom Grill"
                            },
                            {
                                "description": "- Kabis mit Zwiebeln und Kurkuma",
                                "title": "Free - Choice Buffet"
                            }
                        ],
                    }
                ], (other days)
            }


+ Response 503 (application/json)

        There is no data (normal on a weekend)

+ Response 406 (application/json)

        Invalid site value

## Get all sites [/sites/all]

Get information about all sites (upcoming weekdays)

### Get all sites [GET]

+ Response 200 (application/json)

    + Body

            {
                "sites":[
                    {
                        "site":"SiteType.MENSA"
                        "days":[
                            {
                                "weekday":"Fr"
                                "date":"12.05.",
                                "menus":[
                                    {
                                        "description":"Merrfischchnusperli im Bierteig ",
                                        "title":"Fish & Chips"
                                    },
                                    {
                                        "description":"mit Menusalat",
                                        "title":"Älpler Chääs Hörnli"
                                    },
                                    {
                                        "description":"Kräuterbutter, Tagesbeilage und Gemüse vom Free Choice",
                                        "title":"Schweins\u00adsteak vom Grill"
                                    },
                                    {
                                        "description":"- Kabis mit Zwiebeln und Kurkuma",
                                        "title":"Free - Choice Buffet"
                                    }
                                ],
                            }
                        ], (other days)
                    },
                    {
                        "site":"SiteType.FORSCHUNGSZENTRUM"
                        "days":[
                            {
                                "weekday":"Fr",
                                "date":"12.05.",
                                "menus":[
                                    {
                                        "description":"Spaghetti mit verschiedenen Saucen zur Wahl:",
                                        "title":"Spaghetti-Plausch"
                                    },
                                    {
                                        "description":"mit gehobeltem Pecorino",
                                        "title":"Papardelle al Cinque-Pi"
                                    },
                                    {
                                        "description":"mit gebratenem Poulet, Speck,",
                                        "title":"Caesar Salad Classic"
                                    },
                                    {
                                        "description":"Bunter Blattsalat",
                                        "title":"Farmer Salad"
                                    }
                                ],
                            }
                        ], (other days)
                    }
                ]
            }

+ Response 503 (application/json)

        There is no data (normal on a weekend)


## Get a single day for a single site [/sites/{site}/days/{weekday}]

Get information about a single day at a single site

+ Parameters
    + site: mensa (string) - Site name
    + weekday: tue (string) - Weekday name

### Get a single day for a single site [GET]

+ Response 200 (application/json)

    + Body

            {
                "site":"SiteType.MENSA"
                "days":[
                    {
                        "weekday":"Fr"
                        "date":"12.05.",
                        "menus":[
                            {
                                "description":"Merrfischchnusperli im Bierteig ",
                                "title":"Fish & Chips"
                            },
                            {
                                "description":"mit Menusalat",
                                "title":"Älpler Chääs Hörnli"
                            },
                            {
                                "description":"Kräuterbutter, Tagesbeilage und Gemüse vom Free Choice",
                                "title":"Schweins\u00adsteak vom Grill"
                            },
                            {
                                "description":"- Kabis mit Zwiebeln und Kurkuma",
                                "title":"Free - Choice Buffet"
                            }
                        ],
                    }
                ]
            }


+ Response 503 (application/json)

        There is no data (normal on a weekend)

+ Response 404 (application/json)

        No menu for this day

+ Response 406 (application/json)

        Invalid site or weekday value

## Get a single day for all site [/sites/all/days/{weekday}]

Get information about a single day at all sites

+ Parameters
    + weekday: tue (string) - Weekday name

### Get a single day for a single site [GET]

+ Response 200 (application/json)

    + Body

            {
                "sites":[
                    {
                        "site":"SiteType.MENSA"
                        "days":[
                            {
                                "weekday":"Fr"
                                "date":"12.05.",
                                "menus":[
                                    {
                                        "description":"Merrfischchnusperli im Bierteig ",
                                        "title":"Fish & Chips"
                                    },
                                    {
                                        "description":"mit Menusalat",
                                        "title":"Älpler Chääs Hörnli"
                                    },
                                    {
                                        "description":"Kräuterbutter, Tagesbeilage und Gemüse vom Free Choice",
                                        "title":"Schweins\u00adsteak vom Grill"
                                    },
                                    {
                                        "description":"- Kabis mit Zwiebeln und Kurkuma",
                                        "title":"Free - Choice Buffet"
                                    }
                                ],
                            }
                        ]
                    },
                    {
                        "site":"SiteType.FORSCHUNGSZENTRUM"
                        "days":[
                            {
                                "weekday":"Fr",
                                "date":"12.05.",
                                "menus":[
                                    {
                                        "description":"Spaghetti mit verschiedenen Saucen zur Wahl:",
                                        "title":"Spaghetti-Plausch"
                                    },
                                    {
                                        "description":"mit gehobeltem Pecorino",
                                        "title":"Papardelle al Cinque-Pi"
                                    },
                                    {
                                        "description":"mit gebratenem Poulet, Speck,",
                                        "title":"Caesar Salad Classic"
                                    },
                                    {
                                        "description":"Bunter Blattsalat",
                                        "title":"Farmer Salad"
                                    }
                                ],
                            }
                        ]
                    }
                ]
            }

+ Response 503 (application/json)

        There is no data (normal on a weekend)

+ Response 404 (application/json)

        No menu for this day

+ Response 406 (application/json)

        Invalid weekday value